language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 7.3
    - php: 7.4
      env:
        - TEST_COVERAGE=true
    - php: 8.0

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - composer update $DEPENDENCIES

script:
  - if [[ "${TEST_COVERAGE:-false}" == 'true' ]]; then XDEBUG_MODE=coverage php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text; else ./vendor/bin/phpunit; fi
